version: '3.8'

services:

  slashbase-db:
    image: postgres
    container_name: slashbase-db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3

  slashbase-server:
    image: slashbase/slashbase-server
    container_name: slashbase-server
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./data/app/config:/slashbase/config
    depends_on:
      slashbase-db:
        condition: service_healthy

  slashbase-web:
    image: slashbase/slashbase-web
    container_name: slashbase-web
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/ssl/conf:/etc/letsencrypt
      - ./data/ssl/www:/var/www/certbot
