name: development

server:
  port: ":3001"

database:
  host: slashbase-db
  port: 5432
  user: slashbase
  database: slashbase
  password: slashbase

root_user:
  email: paraswaykolecool@gmail.com
  password: paras

secret:
  auth_token_secret: mApzTbbBxaxvdQCp3i0Mc5zd8z9RC1RoQEFdkZ0cHdXERu3zQNMW318tfeLLlfus
  crypted_data_secret_key: ca8f161ccd170f5600f2beb6c17873a69b689ad1be5c5e97513e39b3158643ba

constants:
  api_host: "http://localhost:3001"
  app_host: "http://localhost:3000"

telemetry:
  id: TEST
