version: '3.8'

services:

  slashbase:
    image: slashbaseide/slashbase
    container_name: slashbase
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - app.env
    volumes:
      - ./data:/slashbase/data
